version: '3.1'

services:
  db:
    image: mysql:8.0.33-oracle
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      - ./configs/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeMe
volumes:
  db:
    driver: local
